### ISSUE TITLE
Glint and prettier issues

### ISSUE THREAD

**Issue by mfeckie** [NullVoxPopuli/polaris-starter#7]
Just cloned this repo for a play around and found some challenges in vscode and with glint.

The app seems to build and render fine.

1. All of the `.gts` files show strange glint errors:

<img width="511" alt="Screenshot 2023-08-22 at 8 04 24 pm" src="https://github.com/NullVoxPopuli/polaris-starter/assets/1583673/31d18b40-ded1-4efa-8341-71d52cd26652">
<img width="493" alt="Screenshot 2023-08-22 at 8 04 30 pm" src="https://github.com/NullVoxPopuli/polaris-starter/assets/1583673/4c1d354b-743e-4dd2-b381-288375abc72b">

Running glint directly (glint --build) results in 

```
error TS6504: File '/Users/snip/polaris-starter/app/app.js' is a JavaScript file. Did you mean to enable the 'allowJs' option?
  The file is in the program because:
    Matched by include pattern 'app/**/*' in '/Users/snip/polaris-starter/tsconfig.json'

  tsconfig.json:20:15
    20   "include": ["app/**/*", "tests/**/*", "types/**/*"]
                     ~~~~~~~~~~
    File is matched by include pattern specified here.

error TS6504: File '/Users/snip/polaris-starter/app/router.js' is a JavaScript file. Did you mean to enable the 'allowJs' option?
  The file is in the program because:
    Matched by include pattern 'app/**/*' in '/Users/snip/polaris-starter/tsconfig.json'

  tsconfig.json:20:15
    20   "include": ["app/**/*", "tests/**/*", "types/**/*"]
                     ~~~~~~~~~~
    File is matched by include pattern specified here.

error TS6504: File '/Users/snip/polaris-starter/tests/helpers/index.js' is a JavaScript file. Did you mean to enable the 'allowJs' option?
  The file is in the program because:
    Matched by include pattern 'tests/**/*' in '/Users/snip/polaris-starter/tsconfig.json'

  tsconfig.json:20:27
    20   "include": ["app/**/*", "tests/**/*", "types/**/*"]
                                 ~~~~~~~~~~~~
    File is matched by include pattern specified here.

error TS6504: File '/Users/snip/polaris-starter/tests/test-helper.js' is a JavaScript file. Did you mean to enable the 'allowJs' option?
  The file is in the program because:
    Matched by include pattern 'tests/**/*' in '/Users/snip/polaris-starter/tsconfig.json'

  tsconfig.json:20:27
    20   "include": ["app/**/*", "tests/**/*", "types/**/*"]
                                 ~~~~~~~~~~~~
    File is matched by include pattern specified here.

app/components/excite.ts:16:131 - error TS1127: Invalid character.

16 export const Excite = ({} as typeof import("@glint/environment-ember-template-imports/-private/dsl")).templateExpression(function(𝚪, χ: typeof import("@glint/environment-ember-template-imports/-private/dsl")) {
                                                                                                                                     ~~

app/components/excite.ts:16:133 - error TS1138: Parameter declaration expected.

16 export const Excite = ({} as typeof import("@glint/environment-ember-template-imports/-private/dsl")).templateExpression(function(𝚪, χ: typeof import("@glint/environment-ember-template-imports/-private/dsl")) {
                                                                                                                                       ~

app/components/excite.ts:18:11 - error TS1127: Invalid character.

18     const 𝛄 = χ.emitElement("div");
             ~~

app/components/excite.ts:18:14 - error TS1134: Variable declaration expected.

18     const 𝛄 = χ.emitElement("div");
                ~

```

2. Prettier for `.gts` files fail to format in vscode.  Maybe a vscode specfic issue, but making a change to `welcome.gts` and running `pnpm lint:prettier:fix` leaves the file untouched too.

Error message in code terminal:

```
Error: Invalid version
    at t.isAboveV3 (/Users/snip/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:24715)
    at t.default.getSelectors (/Users/snip/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:11541)
    at t.default.handleActiveTextEditorChanged (/Users/snip/.vscode/extensions/esbenp.prettier-vscode-10.1.0/dist/extension.js:1:10935)
```

3. https://polaris-starter.pages.dev/ seems to result in a 404

**Comment by NullVoxPopuli** [comment]
Thanks for reporting all this!
1. I do see an issue here, and it appears that glint may not be detecting my tsconfig.json :sweat_smile: 
2. vscode does need some config: https://nullvoxpopuli.com/2023-01-04-setting-up-gjs/ (note that you'll want to add stuff to the defaults,  and everyone's existing configs may be a smidge different)
3. bah, thanks -- I'll fix <3

**Comment by NullVoxPopuli** [comment]
latest `main` has the fixes for 1 -- working on 3 now

**Comment by mfeckie** [comment]
Thanks so much
